---

- name: Add PHP PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes

- name: Install PHP {{ php.version }}
  apt:
    name:
      - php-pear
      - php-mysql
      - php{{ php.version }}-cli
      - php{{ php.version }}-common
      - php{{ php.version }}-curl
      - php{{ php.version }}-dev
      - php{{ php.version }}-fpm
      - php{{ php.version }}-gd
      - php{{ php.version }}-imagick
      - php{{ php.version }}-imap
      - php{{ php.version }}-mbstring
      - '{{ "php" + php.version + "-mcrypt"
              if (php.version is version_compare("7.2","<"))
              else [] }}'
      - php{{ php.version }}-mongodb
      - php{{ php.version }}-mysql
      - php{{ php.version }}-soap
      - php{{ php.version }}-xmlrpc
      - php{{ php.version }}-xsl
      - php{{ php.version }}-zip
    state: present
    force: yes

- name: Install mongo driver for php5
  apt:
    name: php{{ php.version }}-mongo
  when: php.version is match("^5.")

- name: Install mongo driver for php7
  apt:
    name: php{{ php.version }}-mongodb
  when: php.version is match("^7.")

- name: Ensure socket directory
  file:
    path: /var/run
    state: directory
  ignore_errors: yes # sometimes it's already a link TODO: check upfront

- name: Start php{{ php.version }}-fpm service
  service:
    name: php{{ php.version }}-fpm
    state: started
    enabled: true

# TODO: move mcrypt to its own file / role
- name: Install mcrypt dependencies
  when: php.version is version_compare("7.2",">=")
  apt:
    name:
      - libmcrypt-dev
      - libreadline-dev
    state: present

- name: Install mcrypt via Pecl
  when: php.version is version_compare("7.2",">=")
  shell: echo "\n\n\n\n\n\n" | pecl install mcrypt-1.0.1 || echo 'mcrypt already installed?'

- name: Add mcrypt so to the ini
  when: php.version is version_compare("7.2",">=")
  lineinfile:
    path: /etc/php/{{ php.version }}/fpm/php.ini
    line: 'extension=mcrypt.so'

- name: Restart PHP
  when: php.version is version_compare("7.2",">=")
  service:
    name: php{{ php.version }}-fpm
    state: restarted
