---
- name: Register if nginx is running
  shell: sudo service nginx status
  register: nginx_running
  ignore_errors: yes

- name: Display if nginx is running
  debug: msg="{{ nginx_running.stdout }}"

- name: Register if elasticsearch is running
  shell: sudo service elasticsearch status
  register: elasticsearch_running
  ignore_errors: yes

- name: Display if elasticsearch is running
  debug: msg="{{ elasticsearch_running.stdout }}"

- name: Register if phpfpm is running
  shell: sudo service php7.0-fpm status
  register: phpfpm_running
  ignore_errors: yes

- name: Display if phpfpm is running
  debug: msg="{{ phpfpm_running.stdout }}"

- name: Register if mongo is running
  shell: sudo service mongod status
  register: mongo_running
  ignore_errors: yes

- name: Display if mongo is running
  debug: msg="{{ mongo_running.stdout }}"

- name: Register if mysql is running
  shell: sudo service mysql status
  register: mysql_running
  ignore_errors: yes

- name: Display if mysql is running
  debug: msg="{{ mysql_running.stdout }}"
