---

- name: 3.0.x Import the public key used by the package management system.
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 7F0CEB10

- name: 3.0.x Create a list file for MongoDB.
  template:
    src: mongodb-org-3.0.list
    dest: /etc/apt/sources.list.d/mongodb-org-3.0.list


