---

- name: Checking essentials
  apt: name="{{ item }}" state=present
  with_items:
  - libmysqlclient-dev

- name: Install mysql
  apt: pkg="mysql-server-{{ mysql.version }}"

- name: Install mysql for python
  pip: name=MySQL-python
