---
# npm ansible command is difficult to use with nvm so just shell it:
- name: Install global npms for grasshopper
  become: no
  shell: source ~/.zshrc && npm install -g bower grunt-cli
  args:
    executable: /bin/zsh

- name: Install sass-css-importer for grasshopper
  gem:
    pre-release: yes
    name: sass-css-importer

- name: Install sass-globbing for grasshopper
  gem:
    name: sass-globbing

- name: Install bundler for grasshopper
  gem:
    name: bundler

- name: Create log location
  file: path=/home/{{ ansible_ssh_user }}/logs state=directory
  become: no
