---
- name: Add Elasticsearch key
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticseach source list file
  lineinfile:
    create: yes
    line: "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
    dest: /etc/apt/sources.list.d/elasticsearch-2.x.list

- name: Elasticsearch
  apt:
    name: elasticsearch=2.1.0
    update_cache: yes

- name: Elasticsearch on boot
  shell: update-rc.d elasticsearch defaults 95 10

- name: Bind to Elasticsearch to localhost
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^network.host:'
    line: "network.host{{ ':' }} {{ elasticsearch.bind }}"

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started