---
- name: Add Elasticsearch key
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticseach source list file
  lineinfile:
    create: yes
    line: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    dest: /etc/apt/sources.list.d/elastic-5.x.list

- name: Install Elasticsearch {{ elasticsearch.version }}
  apt:
    name: elasticsearch={{ elasticsearch.version }}
    update_cache: yes

- name: Elasticsearch on boot
  shell: update-rc.d elasticsearch defaults 95 10

- name: Bind to Elasticsearch to localhost
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^network.host:'
    line: "network.host{{ ':' }} {{ elasticsearch.bind }}"

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
