---
- name: Update Apt
  apt: update_cache=yes

- name: Checking essentials
  apt: name="{{ item }}" state=present
  with_items:
  - build-essential
  - curl
  - htop
  - mailutils
  - wget
  - vim
  - libssl-dev
  - unzip
  - zip

- name: Copy vimrc
  copy: src=.vimrc dest=/home/{{ ansible_ssh_user }}/.vimrc
